apiVersion: intersystems.com/v1alpha1
kind: IrisCluster
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
spec:
  configSource:
    name: iris-config
  licenseKeySecret:
    name: iris-key-secret
  topology:
    data:
      podTemplate:
        spec:
        {{- if .Values.imagePullSecrets }}
          imagePullSecrets:      
{{ toYaml .Values.imagePullSecrets | indent 10 }}
        {{- end }}
      mirrored: {{.Values.mirrored}}
      image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
      updateStrategy:
        type: RollingUpdate
      storageDB:
        resources:
          requests:
            storage: {{.Values.storageDB.size}}
        storageClassName: {{.Values.storageDB.storageClass}}
      storageWIJ:
        resources:
          requests:
            storage: {{.Values.storageWIJ.size}}
        storageClassName: {{.Values.storageWIJ.storageClass}}
      storageJournal1:
        resources:
          requests:
            storage: {{.Values.storageJournal1.size}}
        storageClassName: {{.Values.storageJournal1.storageClass}}
      storageJournal2:
        resources:
          requests:
            storage: {{.Values.storageJournal2.size}}
        storageClassName: {{.Values.storageJournal2.storageClass}}
  serviceTemplate:
      spec:
        type: ClusterIP