deploymentType: "prod"

storageDB: 
  size : 50Gi
  storageClass : local-path
storageWIJ: 
  size: 25Gi
  storageClass : local-path
storageJournal1: 
  size: 50Gi
  storageClass : local-path
storageJournal2: 
  size: 3Gi
  storageClass : local-path

mirrored: false
image:
  registry:  containers.intersystems.com
  repository: iscinternal/sds/base_iris_triage
  tag: 1.0.0

# This will be injected by the control plane:
imagePullSecrets:
 - name: intersystems-container-registry-secret
